Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -43,13 +43,30 @@ runs:
         INPUT_RUN_ID: ${{ inputs.run_id }}
         INPUT_JOB_NAME: ${{ inputs.job_name }}
         INPUT_PER_PAGE: ${{ inputs.per_page }}
-      shell: bash
+      shell: pwsh
       run: |
-        GITHUB_API="/repos/${INPUT_REPOSITORY}/actions/runs/${INPUT_RUN_ID}/jobs"
-        JOBINFO="$(curl --get -Ss -H "Authorization: Bearer ${INPUT_GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "${GITHUB_API_URL}${GITHUB_API}?per_page=${INPUT_PER_PAGE}")"
-        echo "${JOBINFO}" | grep "Resource not accessible by integration" &&  exit 1
-        TOTAL_COUNT="$(echo "${JOBINFO}" | jq -r .total_count)"
-        eval "$(echo "${JOBINFO}" | jq -r --arg job_name "${INPUT_JOB_NAME}" '.jobs | map(select(.name == $job_name)) | .[0] | @sh "JOB_ID=\(.id) HTML_URL=\(.html_url)"')"
-        echo "${JOB_ID}" | grep "null" > /dev/null && echo "parse error, job_id is ${JOB_ID} and total_count is ${TOTAL_COUNT}. 'job_name' or 'per_page' might be wrong. See https://github.com/Tiryoh/gha-jobid-action/blob/main/README.md#inputs" && exit 1
-        echo "job_id=${JOB_ID}" >> "$GITHUB_OUTPUT"
-        echo "html_url=${HTML_URL}" >> "$GITHUB_OUTPUT"
+        $GITHUB_API = "/repos/$env:INPUT_REPOSITORY/actions/runs/$env:INPUT_RUN_ID/jobs"
+        $response = Invoke-RestMethod -Uri "${env:GITHUB_API_URL}$GITHUB_API?per_page=$env:INPUT_PER_PAGE" -Headers @{
+            Authorization = "Bearer $env:INPUT_GITHUB_TOKEN"
+            Accept = "application/vnd.github+json"
+            "X-GitHub-Api-Version" = "2022-11-28"
+        }
+
+        if ($response -like "*Resource not accessible by integration*") {
+            Write-Error "Error: Resource not accessible by integration"
+            exit 1
+        }
+
+        $totalCount = $response.total_count
+        $job = $response.jobs | Where-Object { $_.name -eq $env:INPUT_JOB_NAME } | Select-Object -First 1
+
+        if (-not $job) {
+            Write-Error "Parse error: Job with name '$env:INPUT_JOB_NAME' not found. Total count is $totalCount. 'job_name' or 'per_page' might be wrong. See https://github.com/Tiryoh/gha-jobid-action/blob/main/README.md#inputs"
+            exit 1
+        }
+
+        $job_id = $job.id
+        $html_url = $job.html_url
+
+        "job_id=$job_id" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
+        "html_url=$html_url" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
